#!/bin/bash

if [[ "$1" != "status" ]];then
    echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t" $0 $*
fi

PACKAGE_BASE=${TRIM_APPDEST}
rtw88_firmware_dir="/usr/lib/firmware/rtw88"

supportKernelList=("6.6.38-trim" "6.12.5-trim" "6.12.18-trim")

nowKernelVer=`uname -r`
nowKernelBuildNum=`uname -v| grep -oP '(?<=#)\d+'`

case $1 in
start)
    echo "`uname -a`"
    echo "kernel_inf ${nowKernelVer} ${nowKernelBuildNum}"

    if [[ " ${supportKernelList[@]} " =~ " ${nowKernelVer} " ]]; then
        echo "${nowKernelVer} in supportKernelList"
    else
        echo "${nowKernelVer} not in supportKernelList"
		exit 1
    fi
	
    mkdir -p ${rtw88_firmware_dir}
    cp -rf ${PACKAGE_BASE}/app/rtw88firmware/* ${rtw88_firmware_dir}/
    
    mkdir -p /lib/modules/${nowKernelVer}/updates/dkms/rtw88
    
    case "$nowKernelVer" in
        6.6.38-trim)
            if [[ ${nowKernelBuildNum} -lt 92 ]]; then
                echo "6.6.35-trim lt92 now is not support"
				exit 1
            fi
            if [[ ${nowKernelBuildNum} -ge 92 ]]; then
                echo "debug 6.6.35-trim ge92"
                cp -rf ${PACKAGE_BASE}/app/rtw88_${nowKernelVer}_92/* /lib/modules/${nowKernelVer}/updates/dkms/rtw88/
            fi
            ;;

        6.12.5-trim)
            if [[ ${nowKernelBuildNum} -lt 10 ]]; then
                echo "6.12.5-trim lt10 now is not support"
            fi
            if [[ ${nowKernelBuildNum} -ge 10 ]]; then
                echo "debug 6.12.5-trim ge10"
                cp -rf ${PACKAGE_BASE}/app/rtw88_${nowKernelVer}_10/* /lib/modules/${nowKernelVer}/updates/dkms/rtw88/
            fi
            ;;

        6.12.18-trim)
            echo "debug 6.12.18-trim"
            cp -rf ${PACKAGE_BASE}/app/rtw88_6.12.18-trim_3/* /lib/modules/6.12.18-trim/updates/dkms/rtw88/
            ;;

        *)

    esac
    
    printf "depmod：`depmod`\n"
    printf "`modprobe -v rtw_8812au`\n"
	modlist=`lsmod |grep rtw_8812au | wc -l`
	echo "modnum ${modlist}"
	if [[ ${modlist} -eq 0 ]]; then
		exit 3
	fi
    ;;
stop)

    ;;
status)
    modlist=`lsmod |grep rtw_8812au | wc -l`
    if [[ -d "/lib/modules/${nowKernelVer}/updates/dkms/rtw88" && ! $modlist -eq 0 ]];then
            #echo "is already set"
            exit 0
    else
        echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t" $0 $*
        echo "lsmod rtw"
        printf "`lsmod |grep rtw`\n"
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac